
services:

  mysqldb:
    container_name: mysqlcontainer
    image: mysql:8.0
    platform: linux/amd64
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: likeservice
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAG: prod
      SERVICE_NAME: mysqldb

    networks:
     - internalnet

  nodeapp:
    container_name: nodeappcontainer
    build: .
    # command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm run start'
    image: nodeapp:v1
    platform: linux/amd64
    volumes:
      - $HOME/nodeapp:/code
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - mysqldb
    environment:
      PORT : 8000
      DB_HOST : mysqldb
      DB_USER : root
      DB_PORT : 3306
      DB_NAME : likeservice
      DB_PASSWORD : 'password'
      REDIS_URI : redis://127.0.0.1:6379
      MAIL_SENDER_AUTH : nathanial.fadel@ethereal.email
      MAIL_SENDER_PASS : J8jtJcCgVhWDWAfzRR
      SERVICE_TAG: prod
      SERVICE_NAME: nodeappservice
    networks:
     - internalnet

networks:
  internalnet:
    driver: bridge
