
services:

  mysqldb:
    container_name: mysqlcontainer
    image: mysql:8.0
    platform: linux/amd64
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: likeservice
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAG: prod
      SERVICE_NAME: mysqldb

    networks:
     - internalnet

  
      
    
  nodeapp:
    container_name: likeServiceContainer
    #build: .
    # command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm run start'
    image: ankit2222/likeservice:latest
    platform: linux/amd64
    volumes:
      - $HOME/ankit2222/likeservice:/code
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - mysqldb
    
    environment:
      PORT : 8000
      DB_HOST : mysqldb
      DB_USER : root
      DB_PORT : 3306
      DB_NAME : likeservice
      DB_PASSWORD : 'password'
      REDIS_URI : 'redis://127.0.0.1:6379'
      MAIL_SENDER_AUTH : 'velma10@ethereal.email'
      MAIL_SENDER_PASS : 'ZPyQfGeUw9ua7ykB6q'
      SERVICE_TAG: prod
      SERVICE_NAME: nodeappservice
    networks:
     - internalnet

  redis:
      container_name: rediscontainer
      
      image: redis:6.0.16
      #command: redis-cli 
      restart: always
      ports:
        - 6379:6379
     
        
  # worker:
  #   image: ankit2222/likeservice:latest
  #   depends_on:
  #     - redis
  #   command: npm run worker:dev
  #   links:
  #     - redis
 

networks:
  internalnet:
    driver: bridge
